- name: ensure systemd user dir exists
  file:
    path: "{{ config }}/systemd/user"
    state: directory

- name: get the password for the restic backup
  pause:
    prompt: Password for the restic backup
    private: yes
  register: restic_pw

- name: debug
  debug:
    var: restic_pw

