- name: ensure systemd user dir exists
  file:
    path: "{{ config }}/systemd/user"
    state: directory
    
- name: check env file for local repo
  stat: path="{{ config }}/systemd/user/restic_creds_local.env"
  register: creds_local_f
- name: check env file for remote repo
  stat: path="{{ config }}/systemd/user/restic_creds.env"
  register: creds_f
  
- name: get the remote repo for the restic backups
  pause:
    prompt: remote repo for the restic backups
  register: restic_repo_remote
  when: not creds_f.stat.exists
- name: get the local repo for the restic backups
  pause:
    prompt: local repo for the restic backups
  register: restic_repo_local
  when: not creds_local_f.stat.exists
- name: get the password for the restic backups
  pause:
    prompt: password for the restic backups
    echo: no
  register: restic_pw
  when: not creds_f.stat.exists or not creds_local_f.stat.exists

- name: write remote env file
  copy:
    content: "RESTIC_PASSWORD=\"{{ restic_pw.user_input }}\"\nRESTIC_REPOSITORY=\"{{ restic_repo_remote.user_input }}\""
    dest: "{{ config }}/systemd/user/restic_creds.env"
    mode: "0500"
  when: not creds_f.stat.exists
- name: write local env file
  copy:
    content: "RESTIC_PASSWORD=\"{{ restic_pw.user_input }}\"\nRESTIC_REPOSITORY=\"{{ restic_repo_local.user_input }}\""
    dest: "{{ config }}/systemd/user/restic_creds_local.env"
    mode: "0500"
  when: not creds_local_f.stat.exists

