#!/bin/bash

# short script to select from my projects and open the according tmux session

if [[ $# -eq 1 ]]; then
    # if an argument was given use this as selection target
    selected=$1
else
    items=`find $HOME/repos -maxdepth 1 -mindepth 1 -type d`
    # items+=`find $HOME/Documents -maxdepth 1 -mindepth 1 -type d`

    selected=`echo "$items" | fzf`

    # do nothing if fzf was cancelled
    if [[ -z "$selected" ]]; then
        exit 0
    fi
fi

# get dir name of selected project
dirname=`basename $selected`

# switch to a tmux session with the project dir name
tmux switch-client -t "$dirname"
if [[ $? -eq 0 ]]; then
    exit 0
fi

# if that didn't work create a new session
tmux new-session -c "$selected" -d -s "$dirname" \
    && \
    tmux switch-client -t "$dirname" \
    || tmux new-session -c $selected -A -s $dirname 

